const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForURL(/\/dashboard/i);
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee');
  await page.getByPlaceholder('First Name').fill('Inspect');
  await page.getByPlaceholder('Last Name').fill('Employee');
  await page.locator('.oxd-input-group').filter({ hasText: 'Employee Id' }).locator('input').first().fill('EMP' + Date.now().toString().slice(-5));
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForTimeout(8000);
  const jobTab = page.getByRole('tab', { name: 'Job' });
  await jobTab.click();
  await page.waitForTimeout(2000);
  console.log('job tab text:', await jobTab.textContent());
  console.log('job tab attr:', await jobTab.getAttribute('aria-selected'));
  console.log('contains Job Title:', await page.getByText('Job Title', { exact: false }).count());
  console.log('contains Employment Status:', await page.getByText('Employment Status', { exact: false }).count());
  console.log('body snippet around Job:');
  const bodyText = await page.locator('body').textContent();
  const idx = bodyText.indexOf('Job');
  console.log(bodyText.slice(Math.max(0, idx-500), Math.min(bodyText.length, idx+2500)));
  await browser.close();
})();
