const { chromium } = require('playwright');
(async() => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByPlaceholder('Username').fill('Admin');
  await page.getByPlaceholder('Password').fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.waitForURL(/\/dashboard/i);
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/addEmployee');
  await page.locator('input[placeholder="First Name"]').fill('Tmp');
  await page.locator('input[placeholder="Last Name"]').fill('Person');
  const empField = page.locator('.oxd-input-group').filter({ hasText: 'Employee Id' }).locator('input').first();
  await empField.fill('ABC123');
  console.log('page before click', page.url());
  console.log('emp val', await empField.inputValue());
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForTimeout(5000);
  console.log('page after click', page.url());
  console.log('messages', await page.locator('body').textContent());
  await browser.close();
})();
